// Generated by CoffeeScript 1.10.0
(function() {
  this.app || (this.app = {});

  this.ENTER_KEY = 13;

  $(function() {
    return new app.AppView();
  });

}).call(this);

//# sourceMappingURL=app.js.map
