// Generated by CoffeeScript 1.10.0
(function() {
  Handlebars.registerHelper('xif', function(expression, options) {
    if (Handlebars.helpers['x'].apply(this, [expression, options])) {
      return options.fn(this);
    } else {
      return options.inverse(this);
    }
  });

}).call(this);

//# sourceMappingURL=xif.js.map
