// Generated by CoffeeScript 1.10.0
(function() {
  var TodoList;

  this.app || (this.app = {});

  TodoList = Backbone.Collection.extend({
    model: app.Todo,
    localStorage: new Backbone.LocalStorage('todos-backbone'),
    completed: function() {
      return this.filter(function(todo) {
        return todo.get('completed');
      });
    },
    remaining: function() {
      return this.without.apply(this, this.completed());
    },
    nextOrder: function() {
      if (this.length) {
        return this.last().get('order') + 1;
      } else {
        return 1;
      }
    },
    comparator: function(todo) {
      return todo.get('order');
    }
  });

  app.Todos = new TodoList;

}).call(this);

//# sourceMappingURL=todos.js.map
